return {
  'nvim-lualine/lualine.nvim',
  'neovim/nvim-lspconfig',
  'williamboman/mason.nvim',
  'williamboman/mason-lspconfig.nvim',
  {'nvim-tree/nvim-tree.lua', 
    dependencies = { 'nvim-tree/nvim-web-devicons'}},
  'nvim-lualine/lualine.nvim',
  'jpalardy/vim-slime',
  'vim-test/vim-test',
  'windwp/nvim-autopairs',
  'hiphish/rainbow-delimiters.nvim',
  { "ellisonleao/gruvbox.nvim", 
    priority = 1000 , config = true, 
    opts = {}},
  'numToStr/Comment.nvim',
  'folke/which-key.nvim',
  {'akinsho/bufferline.nvim', 
    version = "*", 
    dependencies = 'nvim-tree/nvim-web-devicons'},
  {'lukas-reineke/indent-blankline.nvim',
    main = 'ibl', opts = {}},
  'RRethy/vim-illuminate',
  -- 'voldikss/vim-floaterm',
  {'akinsho/toggleterm.nvim', 
    version = "*", config = true},
}
