
# Remap prefix key from Ctrl-b to Ctrl-a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Helpful for running Pi
#   https://pi.dev/docs/latest/tmux
set -g extended-keys on
set -g extended-keys-format csi-u

# Vi(m) keys
set -g mode-keys vi

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Changes pane border colors to make active pane easier to see
set -g pane-border-style "fg=blue bg=default"
set -g pane-active-border-style "fg=brightyellow bg=default"
set -g pane-border-format ' #[bold]#P #[default]#{?pane_title,#{pane_title},#{pane_current_command}} '
set -g pane-border-status top

# Set status line color
set -g status-style 'fg=colour11,bg=colour22,bold'

# Clipboard and terminal passthrough
set -g set-clipboard on
set -g allow-passthrough all

# copy to clipboard, MacOS
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"
# copy to clipboard, Linux, X11
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"

bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"
